packages:
  - packages/*

catalog:
  typescript: 5.8.2
  react: 19.1.0
  react-dom: 19.1.0
  vite: 6.2.4
  vite-plugin-checker: 0.9.1
  vite-tsconfig-paths: 5.1.4
  vite-plugin-git-commit-hash: 1.0.7
  vite-plugin-html: 3.2.2
  '@vitejs/plugin-react': 4.3.4
  vitest: 3.2.4
  '@testing-library/dom': 10.4.0
  '@testing-library/jest-dom': 6.6.3
  '@testing-library/react': 16.2.0
  '@testing-library/react-hooks': 8.0.1
  '@testing-library/user-event': 14.6.1
  vitepress: 1.6.3
  zod: 3.25.76
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  '@types/node': 24.0.10
